export const SET_NUMBER_UPDATE = 'SET_NUMBER_UPDATE';
export const SET_CLEAR_CALCULATOR = 'SET_CLEAR_CALCULATOR';
export const SET_RESULT = 'SET_RESULT';
export const SET_NEW_CALCULATION_METHOD = 'SET_NEW_CALCULATION_METHOD';
export const ADD_RESULT = 'ADD_RESULT';
export const REMOVE_RESULT = 'REMOVE_RESULT';